export const projects = [
  {
    id: 9,
    GitHubRepoName: 'crowdfund',
    mainImg: 'crowdfund/desktop.png',
    mainImgAlt: 'Crowdfund product page desktop screenshot',
    modalImg: [
      'crowdfund/desktop.png',
      'crowdfund/tablet.png',
      'crowdfund/mobile.png',
    ],
    modalImgAlt: [
      'Crowdfund product page desktop screenshot',
      'Crowdfund product page tablet screenshot',
      'Crowdfund product page mobile screenshot',
    ],
    title: 'Crowdfund product page',
    desc:
      '<p class="card-text"> A product page for Mastercraft Bamboo Monitor Riser<br> The product is <strong>a beautifully handcrafted monitor stand</strong> to reduce neck and eye strain.</p><p className="card-text"><em>Made with SCSS and React </em></p>',
    URL: 'https://ademkoca.github.io/crowdfund/',
  },
  {
    id: 8,
    GitHubRepoName: 'wordle-clone',
    mainImg: 'wordle/desktop.png',
    mainImgAlt: 'Wordle clone desktop screenshot',
    modalImg: ['wordle/desktop.png', 'wordle/tablet.png', '/wordle/mobile.png'],
    modalImgAlt: [
      'Wordle clone desktop screenshot',
      'Wordle clone tablet screenshot',
      'Wordle clone mobile screenshot',
    ],
    title: 'Wordle clone',
    desc:
      '<p class="card-text"> A clone of the <strong>popular NY Times puzzle game</strong> <a style="color: #212529" href="https://www.nytimes.com/games/wordle/index.html" target="_blank" style="cursor: context-menu;">Wordle</a>. </p><p class="card-text"> This is the initial version of the app. A more advanced version (including light/dark mode switch, stats and "one word per 24 hours" rule is <strong>currently in progress</strong>. </p><p class="card-text"> <em>Made with SCSS and React.</em> </p>',
    URL: 'https://ademkoca.github.io/wordle-clone/',
  },
  {
    id: 0,
    GitHubRepoName: 'weather-app',
    mainImg: 'weatherapp/desktop-dark.png',
    mainImgAlt: 'Weather app desktop screenshot',
    modalImg: [
      'weatherapp/desktop-dark.png',
      'weatherapp/desktop-light.png',
      'weatherapp/tablet-dark.png',
      'weatherapp/tablet-light.png',
      'weatherapp/mobile-dark.png',
      'weatherapp/mobile-light.png',
    ],
    modalImgAlt: [
      'Weather app desktop dark theme screenshot',
      'Weather app desktop light theme screenshot',
      'Weather app tablet dark theme screenshot',
      'Weather app tablet light theme screenshot',
      'Weather app mobile dark theme screenshot',
      'Weather app mobile light theme screenshot',
    ],
    title: 'Weather app',
    desc:
      '<p class="card-text"> Get 24/7 weather data for your location with this <strong>fully responsive, real-time weather app</strong>. </p><p> <small class="card-text"> The theme is automatically switched between <span class="badge bg-light text-dark">light</span> and <span class="badge bg-dark">dark</span> according to the time of the day.</small> </p><p class="card-text"> <em>Made with HTML, CSS (BS 5), JS and <a style="color: #212529" href="https://www.weatherapi.com/" target="_blank" style="cursor: context-menu;">WeatherAPI</a></em> </p>',
    URL: 'https://ademkoca.github.io/weather-app/',
  },
  {
    id: 1,
    GitHubRepoName: 'countries',
    mainImg: 'countries/desktop-dark.png',
    mainImgAlt: 'Countries app dark theme desktop screenshot',
    modalImg: [
      'countries/desktop-dark.png',
      'countries/desktop-light.png',
      'countries/tablet-dark.png',
      'countries/tablet-light.png',
      'countries/mobile-dark.png',
      'countries/mobile-light.png',
    ],
    modalImgAlt: [
      'Weather app dark theme desktop screenshot',
      'Weather app light theme desktop screenshot',
      'Weather app dark theme tablet screenshot',
      'Weather app light theme tablet screenshot',
      'Weather app dark theme mobile screenshot',
      'Weather app light theme mobile screenshot',
    ],
    title: 'Where in the world?',
    desc:
      '<p class="card-text"> <strong>Explore countries</strong> from all parts of the world and <strong>learn more about them</strong>. </p><p> <small class="card-text"> Switch between <span class="badge bg-light text-dark">light</span> and <span class="badge bg-dark">dark</span> theme to your preference.</small> </p><p class="card-text"> <em>Made with HTML, CSS (BS 5), JS and <a style="color: #212529" href="https://restcountries.com/" target="_blank" style="cursor: context-menu;">REST Countries API</a></em> </p>',
    URL: 'https://ademkoca.github.io/countries/',
  },
  {
    id: 2,
    GitHubRepoName: 'todo',
    mainImg: 'todo/desktop-dark.png',
    mainImgAlt: 'TO-DO app dark theme desktop screenshot',
    modalImg: [
      'todo/desktop-dark.png',
      'todo/desktop-light.png',
      'todo/tablet-dark.png',
      'todo/tablet-light.png',
      'todo/mobile-dark.png',
      'todo/mobile-light.png',
    ],
    modalImgAlt: [
      'TO-DO app dark theme desktop screenshot',
      'TO-DO app light theme desktop screenshot',
      'TO-DO app dark theme tablet screenshot',
      'TO-DO app light theme tablet screenshot',
      'TO-DO app dark theme mobile screenshot',
      'TO-DO app light theme mobile screenshot',
    ],
    title: 'TO-DO app',
    desc:
      '<p class="card-text"> Stay organized while balancing work and life activities with this <strong>fully responsive TO-DO app</strong>. </p><p> <small class="card-text"> Switch between <span class="badge bg-light text-dark">light</span> and <span class="badge bg-dark">dark</span> theme to your preference.</small> </p><p class="card-text"> <em>Made with HTML, CSS (BS 5) and JS</em> </p>',
    URL: 'https://ademkoca.github.io/todo/',
  },
  {
    id: 7,
    GitHubRepoName: 'spotify-clone',
    mainImg: 'spotify/desktop.png',
    mainImgAlt: 'Spotify clone desktop screenshot',
    modalImg: ['spotify/desktop.png'],
    modalImgAlt: ['Spotify clone desktop screenshot'],
    title: 'Spotify clone',
    desc:
      '<p class="card-text">Desktop version of Spotify homepage.</p><p class="card-text"> <em>Made with HTML and SCSS.</em> </p>',
    URL: 'https://ademkoca.github.io/spotify-clone/',
  },
  {
    id: 3,
    GitHubRepoName: 'social-media-dashboard-with-theme-switch',
    mainImg: 'social-dashboard/desktop-dark.png',
    mainImgAlt: 'Social media dashboard dark theme desktop screenshot',
    modalImg: [
      'social-dashboard/desktop-dark.png',
      'social-dashboard/desktop-light.png',
      'social-dashboard/tablet-dark.png',
      'social-dashboard/tablet-light.png',
      'social-dashboard/mobile-dark.png',
      'social-dashboard/mobile-light.png',
    ],
    modalImgAlt: [
      'Social media dashboard dark theme desktop screenshot',
      'Social media dashboard light theme desktop screenshot',
      'Social media dashboard dark theme tablet screenshot',
      'Social media dashboard light theme tablet screenshot',
      'Social media dashboard dark theme mobile screenshot',
      'Social media dashboard light theme mobile screenshot',
    ],
    title: 'Social media dashboard',
    desc:
      '<p class="card-text"> Track your social media accounts\' statistics using this <strong>fully responsive social media dashboard</strong>. </p><p> <small class="card-text"> Switch between <span class="badge bg-light text-dark">light</span> and <span class="badge bg-dark">dark</span> theme to your preference.</small> </p><p class="card-text"> <em>Made with HTML, CSS (BS 5) and JS</em> </p>',
    URL: 'https://ademkoca.github.io/social-media-dashboard-with-theme-switch/',
  },
  {
    id: 4,
    GitHubRepoName: 'intro-component-with-signup-form',
    mainImg: 'register/desktop.png',
    mainImgAlt: 'Register form desktop screenshot',
    modalImg: [
      'register/desktop.png',
      'register/tablet.png',
      'register/mobile.png',
    ],
    modalImgAlt: [
      'Register form desktop screenshot',
      'Register form tablet screenshot',
      'Register form mobile screenshot',
    ],
    title: 'Register form',
    desc:
      '<p class="card-text"> Make your website stand out using this <strong>fully responsive register form</strong>. </p><p class="card-text"> <em>Made with HTML, CSS (BS 5) and JS</em> </p>',
    URL: 'https://ademkoca.github.io/intro-component-with-signup-form/',
  },
  {
    id: 5,
    GitHubRepoName: 'search-bio',
    mainImg: 'search-bio/desktop-gallery.png',
    mainImgAlt: "Search artists' bio homepage desktop screenshot",
    modalImg: [
      'search-bio/desktop-bio.png',
      'search-bio/desktop-gallery.png',
      'search-bio/tablet-bio.png',
      'search-bio/tablet-gallery.png',
      'search-bio/mobile-bio.png',
      'search-bio/mobile-gallery.png',
    ],
    modalImgAlt: [
      "Search artists' bio desktop homepage screenshot",
      "Search artists' bio tablet gallery screenshot",
      "Search artists' bio mobile homepage screenshot",
      "Search artists' bio desktop gallery screenshot",
      "Search artists' bio tablet homepage screenshot",
      "Search artists' bio mobile gallery screenshot",
    ],
    title: "Search artists' bio",
    desc:
      '<p class="card-text"> Search for your favorite artist/band biography and photos using this <strong>fully responsive website</strong>. </p><p class="card-text"> <em>Made with HTML, CSS (BS 5), JS and <a style="color: #212529" href="https://theaudiodb.com/" target="_blank" style="cursor: context-menu;">TheAudioDB</a></em> </p>',
    URL: 'https://ademkoca.github.io/search-bio/',
  },
  {
    id: 6,
    GitHubRepoName: 'cats',
    mainImg: 'cats/desktop.png',
    mainImgAlt: 'Random cat facts desktop screenshot',
    modalImg: ['cats/desktop.png', 'cats/tablet.png', 'cats/mobile.png'],
    modalImgAlt: [
      'Random cat facts desktop screenshot',
      'Random cat facts tablet screenshot',
      'Random cat facts mobile screenshot',
    ],
    title: 'Random cat facts',
    desc:
      '<p class="card-text"> Every now and then take a break from your hard work and entertain yourself with this <strong>fully responsive random cat facts generator</strong>. </p><p class="card-text"> <em>Made with HTML, CSS (BS 5) JS and <a style="color: #212529" href="https://catfact.ninja/" target="_blank" style="cursor: context-menu;">Cat Facts API</a></em> </p>',
    URL: 'https://ademkoca.github.io/cats/',
  },
];
