export const projects = [
  {
    id: 9,
    GitHubRepoName: 'crowdfund',
    date: 'crowdfund-life',
    mainImg: 'crowdfund/desktop.png',
    mainImgAlt: 'Crowdfund product page desktop screenshot',
    modalImg: [
      'crowdfund/desktop.png',
      'crowdfund/tablet.png',
      'crowdfund/mobile.png',
    ],
    modalImgAlt: [
      'Crowdfund product page desktop screenshot',
      'Crowdfund product page tablet screenshot',
      'Crowdfund product page mobile screenshot',
    ],
    title: 'Crowdfund product page',
    desc: '<p class="card-text"> A product page for Mastercraft Bamboo Monitor Riser<br> The product is <strong>a beautifully handcrafted monitor stand</strong> to reduce neck and eye strain.</p><p className="card-text"><em>Made with SCSS and React </em></p>',
    URL: 'https://ademkoca.github.io/crowdfund/',
  },
  {
    id: 8,
    GitHubRepoName: 'wordle-clone',
    date: 'wordle-life',
    mainImg: 'wordle/desktop.png',
    mainImgAlt: 'Wordle clone desktop screenshot',
    modalImg: ['wordle/desktop.png', 'wordle/tablet.png', '/wordle/mobile.png'],
    modalImgAlt: [
      'Wordle clone desktop screenshot',
      'Wordle clone tablet screenshot',
      'Wordle clone mobile screenshot',
    ],
    title: 'Wordle clone',
    desc: '<p class="card-text"> A clone of the <strong>popular NY Times puzzle game</strong> <a href="https://www.nytimes.com/games/wordle/index.html" target="_blank" style="cursor: context-menu;">Wordle</a>. </p><p class="card-text"> This is the initial version of the app. A more advanced version (including light/dark mode switch, stats and "one word per 24 hours" rule is <strong>currently in progress</strong>. </p><p class="card-text"> <em>Made with SCSS and React.</em> </p>',
    URL: 'https://ademkoca.github.io/wordle-clone/',
  },
  {
    id: 0,
    GitHubRepoName: 'weather-app',
    date: 'weather-app',
    mainImg: 'weatherapp/desktop.png',
    mainImgAlt: 'Weather app desktop screenshot',
    modalImg: [
      'weatherapp/desktop-light.png',
      'weatherapp/desktop-dark.png',
      'weatherapp/tablet-light.png',
      'weatherapp/tablet-dark.png',
      'weatherapp/mobile-light.png',
      'weatherapp/mobile-dark.png',
    ],
    modalImgAlt: [
      'Weather app desktop light theme screenshot',
      'Weather app desktop dark theme screenshot',
      'Weather app tablet light theme screenshot',
      'Weather app tablet dark theme screenshot',
      'Weather app mobile light theme screenshot',
      'Weather app mobile dark theme screenshot',
    ],
    title: 'Weather app',
    desc: '<p class="card-text"> Get 24/7 weather data for your location with this <strong>fully responsive, real-time weather app</strong>. </p><p> <small class="card-text"> The theme is automatically switched between <span class="badge bg-light text-dark">light</span> and <span class="badge bg-dark">dark</span> according to the time of the day.</small> </p><p class="card-text"> <em>Made with HTML, CSS (BS 5), JS and <a href="https://www.weatherapi.com/" target="_blank" style="cursor: context-menu;">WeatherAPI</a></em> </p>',
    URL: 'https://ademkoca.github.io/weather-app/',
  },
];
